Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/apps/chatbot/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/apps/chatbot/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/apps/chatbot/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/apps/chatbot/__init__.py changed, reloading.
Watching for file changes with StatReloader
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/apps/chatbot/__init__.py changed, reloading.
Watching for file changes with StatReloader
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/apps/documents/__init__.py changed, reloading.
Watching for file changes with StatReloader
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/apps/documents/__init__.py changed, reloading.
Watching for file changes with StatReloader
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/apps/documents/admin.py changed, reloading.
Watching for file changes with StatReloader
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/apps/documents/admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/embassy_website/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/apps/services/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/embassy_website/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/embassy_website/settings.py changed, reloading.
Watching for file changes with StatReloader
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/apps/accounts/forms.py changed, reloading.
Watching for file changes with StatReloader
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/apps/accounts/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/apps/accounts/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/apps/accounts/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/apps/accounts/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: cms/home.html
"GET / HTTP/1.1" 500 76534
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: cms/home.html
"GET / HTTP/1.1" 500 76671
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: cms/home.html
"GET / HTTP/1.1" 500 76671
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: cms/home.html
"GET / HTTP/1.1" 500 76534
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: cms/home.html
"GET / HTTP/1.1" 500 76671
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: cms/home.html
"GET / HTTP/1.1" 500 76671
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: cms/home.html
"GET / HTTP/1.1" 500 76671
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: cms/home.html
"GET / HTTP/1.1" 500 76671
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: cms/home.html
"GET / HTTP/1.1" 500 76671
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: cms/home.html
"GET / HTTP/1.1" 500 76671
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: cms/home.html
"GET / HTTP/1.1" 500 76671
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: cms/home.html
"GET / HTTP/1.1" 500 76671
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: cms/home.html
"GET / HTTP/1.1" 500 76671
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: cms/home.html
"GET / HTTP/1.1" 500 76671
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: cms/home.html
"GET / HTTP/1.1" 500 76671
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: cms/home.html
"GET / HTTP/1.1" 500 76671
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: cms/home.html
"GET / HTTP/1.1" 500 76534
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 5226
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4195
"GET /static/admin/css/base.css HTTP/1.1" 200 21310
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2694
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2929
"GET /static/admin/css/login.css HTTP/1.1" 200 958
"GET /static/admin/css/responsive.css HTTP/1.1" 200 18559
"GET /static/admin/js/theme.js HTTP/1.1" 200 1943
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4355
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4355
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 15426
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /admin/appointments/appointmentslot/add/ HTTP/1.1" 200 17980
"GET /static/admin/css/forms.css HTTP/1.1" 200 9090
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
"GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
"GET /static/admin/js/core.js HTTP/1.1" 200 5682
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11921
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 292458
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 8943
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /static/admin/js/actions.js HTTP/1.1" 200 7872
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
"POST /admin/appointments/appointmentslot/add/ HTTP/1.1" 200 18161
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/img/calendar-icons.svg HTTP/1.1" 200 1094
Internal Server Error: /admin/appointments/appointmentslot/add/
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: appointments_appointmentslot

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1792, in _changeform_view
    form_validated = form.is_valid()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/forms/forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/forms/forms.py", line 435, in full_clean
    self._post_clean()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/forms/models.py", line 492, in _post_clean
    self.validate_unique()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/forms/models.py", line 501, in validate_unique
    self.instance.validate_unique(exclude=exclude)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/db/models/base.py", line 1229, in validate_unique
    errors = self._perform_unique_checks(unique_checks)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/db/models/base.py", line 1339, in _perform_unique_checks
    if qs.exists():
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/db/models/query.py", line 1241, in exists
    return self.query.has_results(using=self.db)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/db/models/sql/query.py", line 598, in has_results
    return compiler.has_results()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1530, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: appointments_appointmentslot
"POST /admin/appointments/appointmentslot/add/ HTTP/1.1" 500 191422
"GET / HTTP/1.1" 200 5226
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 5226
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'get_current_language'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 2: 'get_current_language'. Did you forget to register or load this tag?
"GET / HTTP/1.1" 500 191483
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 28642
"GET /static/css/main.css HTTP/1.1" 200 15458
"GET /static/js/main.js HTTP/1.1" 200 11386
"GET /static/js/chatbot.js HTTP/1.1" 200 14112
"GET /static/images/favicon.ico HTTP/1.1" 404 1914
Not Found: /sw.js
"GET /sw.js HTTP/1.1" 404 3225
Internal Server Error: /chatbot/chat/
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/apps/chatbot/views.py", line 13, in chatbot_view
    return render(request, 'chatbot/chat.html', {
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: chatbot/chat.html
"POST /chatbot/chat/ HTTP/1.1" 500 78119
Internal Server Error: /chatbot/chat/
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/apps/chatbot/views.py", line 13, in chatbot_view
    return render(request, 'chatbot/chat.html', {
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: chatbot/chat.html
"POST /chatbot/chat/ HTTP/1.1" 500 78119
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/apps/cms/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/apps/cms/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/linoospaulinos/python_project_2025/testweb/embassy-mozambique-website/src/apps/cms/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 32230
"GET /static/js/main.js HTTP/1.1" 304 0
"GET /static/css/main.css HTTP/1.1" 200 16684
Not Found: /sw.js
"GET /sw.js HTTP/1.1" 404 3225
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 698, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 606, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'mul'
"GET / HTTP/1.1" 500 259024
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 698, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Users/linoospaulinos/miniforge3/envs/py-learn-py310/lib/python3.10/site-packages/django/template/base.py", line 606, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'mul'
"GET / HTTP/1.1" 500 259024
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 17768
"GET /static/css/main.css HTTP/1.1" 200 16875
